### ISSUE TITLE
Backporting fix for protobuf and gazebo (at least)

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libprotobuf-feedstock#206]
### Comment:

Could we backport:
https://github.com/protocolbuffers/protobuf/commit/bb4718cd8720c6acb17b58b19f8345c94aaaba78

it seems to be affecting tensorflow https://github.com/conda-forge/tensorflow-feedstock/pull/371
and gazebo: https://github.com/conda-forge/gazebo-feedstock/pull/201

cc: @traversaro @Tobias-Fischer

**Comment by h-vetinari** [comment]
Hm, seems this patch hasn't been backported to the 25.x line (though 26.x already has a RC out).

If it's urgent, we'll have to create a branch for 4.25.1. Otherwise, I was planning to migrate grpc 1.61 & abseil 20240108 & protobuf 4.25.2 soon (which means we could add the patch on top of main here)

**Comment by hmaarrfk** [comment]
tensorflow cant be built without it.

happy to skip one combo of libabseil

**Comment by traversaro** [comment]
> tensorflow cant be built without it.
> 
> happy to skip one combo of libabseil

Same for gazebo, thanks!

**Comment by h-vetinari** [comment]
Nevermind, I misremembered that I hadn't merged https://github.com/conda-forge/libprotobuf-feedstock/pull/202 yet. So let's go with #207 and then I'll rebase #202
